[theme]
primaryColor = "#4A39C0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9F8FF"
textColor = "#1A1A2E"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
